# Generated by Django 5.0.6 on 2024-06-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='ник в ТГ'),
        ),
        migrations.AddField(
            model_name='user',
            name='time_left',
            field=models.IntegerField(default=100, verbose_name='оставшееся время'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='почта'),
        ),
    ]
