# docker-compose.yml

services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5441:5432"
    networks:
      - web_insight

  web_app:
    image: docker.io/sp1kex/web_insight:${IMAGE_TAG:-latest}
    command: make start_app
    ports:
      - '8001:8001'
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    networks:
      - web_insight

  listener:
    image: docker.io/sp1kex/web_insight:${IMAGE_TAG:-latest}
    command: make run_listener
    depends_on:
      - db
      - web_app
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    networks:
      - web_insight


networks:
  web_insight:
    external: True
