services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5441:5441"

  web_app:
    image: docker.io/almaz1994/web_insight:latest
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code
    ports:
      - '8001:8001'
    depends_on:
      - db
    environment:
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5441