# Generated by Django 5.0.6 on 2024-05-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryYoutube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcription', models.TextField(blank=True, null=True, verbose_name='транскрипция')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='саммари')),
                ('transcription_is_ready', models.BooleanField(default=False, verbose_name='транскрипция готова')),
                ('summary_is_ready', models.BooleanField(default=False, verbose_name='саммари готов')),
                ('worker_db_id', models.IntegerField(blank=True, null=True, verbose_name='ИД результата в БД воркера')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата и время запроса')),
                ('script', models.CharField(choices=[('Протокол встречи', 'Протокол встречи'), ('Саммари записи', 'Саммари записи'), ('Резюме консультации', 'Резюме консультации'), ('Содержание лекции', 'Содержание лекции')], default='Саммари записи', max_length=40, verbose_name='сценарий обработки')),
                ('prompt', models.TextField(blank=True, null=True, verbose_name='Промт пользователя')),
                ('link', models.CharField(max_length=100, verbose_name='ссылка')),
            ],
            options={
                'verbose_name': 'запрос со ссылкой',
                'verbose_name_plural': 'запросы со ссылкой',
            },
        ),
    ]
