# Generated by Django 5.0.6 on 2024-05-30 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100, verbose_name='ссылка')),
                ('transcription', models.TextField(blank=True, null=True, verbose_name='транскрипция')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='саммари')),
                ('transcription_is_ready', models.BooleanField(default=False, verbose_name='транскрипция готова')),
                ('summary_is_ready', models.BooleanField(default=False, verbose_name='саммари готов')),
                ('worker_db_id', models.IntegerField(blank=True, null=True, verbose_name='ИД результата в БД воркера')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата и время запроса')),
                ('script', models.CharField(choices=[('Протокол встречи', 'Протокол встречи'), ('Саммари записи', 'Саммари записи'), ('Резюме консультации', 'Резюме консультации'), ('Содержание лекции', 'Содержание лекции')], default='Саммари записи', max_length=40, verbose_name='сценарий обработки')),
                ('prompt', models.TextField(blank=True, null=True, verbose_name='Промт пользователя')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'запрос к воркеру',
                'verbose_name_plural': 'запросы к воркеру',
            },
        ),
        migrations.DeleteModel(
            name='SummaryYoutube',
        ),
    ]
