# Generated by Django 5.0.6 on 2024-05-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_summary_delete_summaryyoutube'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio_files/', verbose_name='аудио файл'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ссылка'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='transcription',
            field=models.TextField(blank=True, null=True, verbose_name='транскрибация'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='transcription_is_ready',
            field=models.BooleanField(default=False, verbose_name='транскрибация готова'),
        ),
    ]
