# Generated by Django 5.0.6 on 2024-05-30 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_summary_audio_file_alter_summary_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='link',
            new_name='youtube_link',
        ),
    ]
