# Generated by Django 5.0.6 on 2024-06-07 12:51

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_summary_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[main.validators.validate_youtube_url], verbose_name='Youtube ссылка'),
        ),
    ]
