# Generated by Django 5.0.6 on 2024-06-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_summary_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='file_link_s3',
            field=models.TextField(blank=True, null=True, verbose_name='ссылка на файл в s3'),
        ),
    ]
