# Generated by Django 5.0.6 on 2024-07-06 12:23

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_summary_file_link_s3'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='unique_id',
            field=models.CharField(default=main.models.generate_uuid, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='script',
            field=models.CharField(max_length=40, verbose_name='сценарий обработки'),
        ),
    ]
