# Generated by Django 5.0.6 on 2024-07-06 13:05

import django.db.models.deletion
import main.models
import main.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_summary_unique_id_alter_summary_script'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SummariesAndTranscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcription', models.TextField(blank=True, null=True, verbose_name='транскрибация')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='саммари')),
            ],
            options={
                'verbose_name': 'саммари и транскрибация',
                'verbose_name_plural': 'саммари и транскрибации',
            },
        ),
        migrations.RemoveField(
            model_name='summary',
            name='worker_db_id',
        ),
        migrations.CreateModel(
            name='S3Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=main.models.generate_uuid, max_length=100, unique=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='сессия')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio_files/', verbose_name='аудио файл')),
                ('file_link_s3', models.TextField(blank=True, null=True, verbose_name='ссылка на файл в s3')),
                ('transcription_is_ready', models.BooleanField(default=False, verbose_name='транскрибация готова')),
                ('summary_is_ready', models.BooleanField(default=False, verbose_name='саммари готов')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата и время запроса')),
                ('script', models.CharField(max_length=40, verbose_name='сценарий обработки')),
                ('prompt', models.TextField(blank=True, null=True, verbose_name='Промт пользователя')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('summary_and_transcriptions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.summariesandtranscriptions')),
            ],
            options={
                'verbose_name': 's3 запрос',
                'verbose_name_plural': 's3 запросы',
            },
        ),
        migrations.CreateModel(
            name='YoutubeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=main.models.generate_uuid, max_length=100, unique=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='сессия')),
                ('youtube_link', models.CharField(blank=True, max_length=100, null=True, validators=[main.validators.validate_youtube_url], verbose_name='Youtube ссылка')),
                ('transcription_is_ready', models.BooleanField(default=False, verbose_name='транскрибация готова')),
                ('summary_is_ready', models.BooleanField(default=False, verbose_name='саммари готов')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата и время запроса')),
                ('script', models.CharField(max_length=40, verbose_name='сценарий обработки')),
                ('prompt', models.TextField(blank=True, null=True, verbose_name='Промт пользователя')),
                ('summary_and_transcriptions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.summariesandtranscriptions')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'запрос к воркеру',
                'verbose_name_plural': 'запросы к воркеру',
            },
        ),
    ]
